# prod DB
.db:
  cred_file: cred.json
  project_id: badenbattle-a0dec
# dev DB
db:
  cred_file: cred-dev.json
  project_id: mailmerge-59e91
csv:
  delimiter: ";"
  headers:
    name: Nom
    city: Localité
    unit: Unité
    category: Section
    nb_teams: Equipes
    nb_players: Total par équipe
firestore:
  teams_collection   : teams
  games_collection   : games
  matches_collection : matches
  sections_collection: sections
  settings_collection: settings
  profiles_collection: users
  settings_document  : app